HotelCloudBedSystem/ViewModels/ManagerRegisterationViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HotelCloudBedSystem.ViewModels
{
    public class ManagerRegisterationViewModel
    {
     
        public string FirstName { get; set; }

        
        public string LastName { get; set; }


        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        public string  PhoneNo { get; set; }

        public string  Address { get; set; }

        [StringLength(2000)]
        public string Aboutyou { get; set; }


        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

    }
}

HotelCloudBedSystem/Areas/Identity/Pages/Account/Register.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using HotelCloudBedSystem.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authentication;
using System.Linq;

namespace HotelCloudBedSystem.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;
        private readonly RoleManager<AppRole> _roleManager;

        public RegisterModel(
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager,
            ILogger<RegisterModel> logger,
            IEmailSender emailSender,
            RoleManager<AppRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            _roleManager = roleManager;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }
        public IList<AuthenticationScheme> ExternalLogins { get; set; }
        public class InputModel
        {

            [Required]
            public string FirstName { get; set; }

            [Required]
            public string LastName { get; set; }


            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public async Task OnGet(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync().ConfigureAwait(true)).ToList();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (ModelState.IsValid)
            {
                var user = new AppUser
                {
                    FirstName = Input.FirstName,
                    LastName = Input.LastName,
                    UserName = Input.Email,
                    Email = Input.Email,
                    IsEnable = true,
                    RequestAccept = true
                };
                var result = await _userManager.CreateAsync(user, Input.Password).ConfigureAwait(true);
                if (result.Succeeded)
                {

                    var roles = _roleManager.Roles;
                    int count = 0;
                    foreach (var role in roles)
                    {
                        var userrole = _userManager.IsInRoleAsync(user, role.Name).Result;
                        if (userrole == true)
                        {
                            count++;
                        }

                    }
                    if (count == 0)
                    {
                        var result1 = await _userManager.AddToRoleAsync(user, "User").ConfigureAwait(true);
                        var UserByEmail = _userManager.FindByEmailAsync(Input.Email).Result;
                        var rolebyname = _roleManager.FindByNameAsync("User").Result;
                        if (UserByEmail != null)
                        {
                            UserByEmail.AppRole = rolebyname;

                            await _userManager.UpdateAsync(UserByEmail);
                        }
                    }
                    _logger.LogInformation("User created a new account with password.");

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user).ConfigureAwait(true);
                    var callbackUrl = Url.Page(
                        "/Account/ConfirmEmail",
                        pageHandler: null,
                        values: new { userId = user.Id, code = code },
                        protocol: Request.Scheme);

                    await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
                        $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.").ConfigureAwait(true);


                    return LocalRedirect(returnUrl);
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

HotelCloudBedSystem/Controllers/ManagerRegisterationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HotelCloudBedSystem.Models;
using HotelCloudBedSystem.Services;
using HotelCloudBedSystem.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;

namespace HotelCloudBedSystem.Controllers
{
    public class ManagerRegisterationController : Controller
    {
        private UserManager<AppUser> _userManager;
        private RoleManager<AppRole> _roleManager;
        private IEmailSender _emailSender;
        private ISmsSender _msSender;

        public ManagerRegisterationController(UserManager<AppUser> userManager,
            RoleManager<AppRole> roleManager ,
             IEmailSender emailSender,
            ISmsSender msSender)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _emailSender = emailSender;
            _msSender = msSender;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(ManagerRegisterationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser()
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    PhoneNumber = model.PhoneNo,
                    Aboutyou = model.Aboutyou,
                    Address = model.Address,
                    UserName=model.Email,
                    RequestAccept=false,
                    IsEnable=true

                };

                var result = await _userManager.CreateAsync(user, model.Password).ConfigureAwait(true);
                if (result.Succeeded)
                {
                    await _emailSender.SendEmailAsync(user.Email, "You have been registered as manager",
                     $"Now Register your Hotel")
                   .ConfigureAwait(true);
                    await _msSender.SendSmsAsync(user.PhoneNumber, "You have been registered as manager" +
                        "Now Register your Hotel").ConfigureAwait(true);
                    var roles = _roleManager.Roles;
                    int count = 0;
                    foreach (var role in roles)
                    {
                        var userrole = _userManager.IsInRoleAsync(user, role.Name).Result;
                        if (userrole == true)
                        {
                            count++;
                        }

                    }
                    if (count == 0)
                    {
                        var result1 = await _userManager.AddToRoleAsync(user, "Manager").ConfigureAwait(true);
                    }
                    return RedirectToAction("HotelRegister", "HotelRegisteration", new { email = model.Email });
                }
            }
                return View();
        }
    }
}

HotelCloudBedSystem/Views/ManagerRegisteration/Register.cshtml
@model HotelCloudBedSystem.ViewModels.ManagerRegisterationViewModel

@{
    ViewData["Title"] = "Register";
}

<style>
    #boxshadow {
        position: relative;
        box-shadow: 1px 2px 4px rgba(0, 0, 0, .5);
        padding: 10px;
        background: white;
    }

        #boxshadow::after {
            content: '';
            position: absolute;
            z-index: -1; /* hide shadow behind image */
            box-shadow: 0 15px 20px rgba(0, 0, 0, 0.3);
            width: 70%;
            left: 15%; /* one half of the remaining 30% */
            height: 100px;
            bottom: 0;
        }
    #Subbtn {
        background-color: #02598f;
        border: none;
        color: white;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        border: 1px solid #6d7b84;
    }
</style>



<div class="card shadow-sm border-light mb-3" >
    <div class="card-header" style="background-color:#02598f">
        <h5 style="color:#D4AC0D">
            <i class="fa fa-user-circle-o"></i><span style="        color: white
"> Manager Registeration</span> 
        </h5>
    </div>
    <div class="card-body" style="background-color:white">
        <div class="row">
            <div class="col-md-7">
                <section>
                    <form asp-area=""
                          asp-controller="ManagerRegisteration" asp-action="Register" method="post">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger small text-uppercase" })
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label asp-for="FirstName">FirstName</label>
                                <input asp-for="FirstName" class="form-control" id="firstname" placeholder="Firstname">
                                <span asp-validation-for="FirstName"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="LastName">LastName</label>
                                <input asp-for="LastName" class="form-control" id="lastname" placeholder="Lastname">
                                <span asp-validation-for="LastName"></span>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label asp-for="Email">Email</label>
                                <input asp-for="Email" class="form-control" id="email" placeholder="email">
                                <span asp-validation-for="Email"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="PhoneNo">Phone No</label>
                                <input asp-for="PhoneNo" class="form-control" id="pno" placeholder="+92235.....">
                                <span asp-validation-for="PhoneNo"></span>
                            </div>
                        </div>
                        <div class="form-group " >
                            <label asp-for="Address">Address</label>
                            <input asp-for="Address" class="form-control" id="inputAddress" placeholder="1234 Main St" style="width:750px;">
                            <span asp-validation-for="Address"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Aboutyou">About You</label>
                            <input asp-for="Aboutyou" class="form-control" id="inputAddress" placeholder="info....." style="width:750px;">
                            <span asp-validation-for="Aboutyou"></span>
                        </div>

                        <div class="form-row" style="margin-top:5px;">
                            <div class="form-group col-md-6">
                                <label asp-for="Password">Password</label>
                                <input asp-for="Password" class="form-control" id="pass" placeholder="password***">
                                <span asp-validation-for="Password"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="ConfirmPassword">Confirm Password</label>
                                <input asp-for="ConfirmPassword" class="form-control" id="cpass" placeholder="CPassword***">
                                <span asp-validation-for="ConfirmPassword"></span>
                            </div>
                        </div>


                        <button type="submit"
                                style="width:750px;height:47px;font-weight:500" id="Subbtn">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Register
                        </button>
                    </form>
                </section>
            </div>
            <div class="col-md-5">
                <section>
                    <h4>Register As Manager Here!.</h4>
                    <hr />
                            <div>
                                <p>
                                    There are no external authentication services configured. See <a href="https://go.microsoft.com/fwlink/?LinkID=532715">this article</a>
                                    for details on setting up this ASP.NET application to support logging in via external services.
                                </p>
                            </div>
                            <img src="~/image/dd.jpg" style="width:350px;
                             height:350px;margin-left:100px;margin-top:-20px"/>
                        </section>
            </div>
        </div>
       

    </div>

</div>